# Form implementation generated from reading ui file 'list_dlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_List_Dialog(object):
    def setupUi(self, List_Dialog):
        List_Dialog.setObjectName("List_Dialog")
        List_Dialog.resize(1000, 495)

        self.retranslateUi(List_Dialog)
        QtCore.QMetaObject.connectSlotsByName(List_Dialog)

    def retranslateUi(self, List_Dialog):
        _translate = QtCore.QCoreApplication.translate
        List_Dialog.setWindowTitle(_translate("List_Dialog", "Dialog"))
